FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    libpq-dev \
    tesseract-ocr \
    poppler-utils \
    && rm -rf /var/lib/apt/lists/*

# Install python dependencies
COPY requirements.txt .
RUN pip install --default-timeout=1000 -r requirements.txt

# Copy alembic migrations and configuration
COPY alembic.ini .
COPY alembic/ ./alembic/

# Copy application code
COPY app/ ./app/

CMD ["celery", "-A", "app.worker.celery_app", "worker", "--loglevel=info"]
